resolver: lts-12.22
extra-deps:
  - git: https://github.com/MartinRell/content-api-haskell-client.git
    commit: 8e2f95d1d695ccf774259af607742440d74573de
    subdirs:
      - guardian-content-api-client
